<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \App\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'Nom_cat', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'Description_cat', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'image_cate', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'thumbnail', 'PhotoPath'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'Nom_cat', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'Description_cat', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'image_cate', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'thumbnail', 'PhotoPath'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCat', []);

        return parent::getNomCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCat(string $Nom_cat): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCat', [$Nom_cat]);

        return parent::setNomCat($Nom_cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionCat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionCat', []);

        return parent::getDescriptionCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionCat(string $Description_cat): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionCat', [$Description_cat]);

        return parent::setDescriptionCat($Description_cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageCate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageCate', []);

        return parent::getImageCate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageCate(?string $image_cate): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageCate', [$image_cate]);

        return parent::setImageCate($image_cate);
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\App\Entity\Article $article): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', [$article]);

        return parent::addArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\App\Entity\Article $article): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', [$article]);

        return parent::removeArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function addSousCategory(\App\Entity\SousCategorie $sousCategory): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSousCategory', [$sousCategory]);

        return parent::addSousCategory($sousCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSousCategory(\App\Entity\SousCategorie $sousCategory): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSousCategory', [$sousCategory]);

        return parent::removeSousCategory($sousCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getthumbnail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getthumbnail', []);

        return parent::getthumbnail();
    }

    /**
     * {@inheritDoc}
     */
    public function setthumbnail(\Symfony\Component\HttpFoundation\File\File $thumbnail = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setthumbnail', [$thumbnail]);

        return parent::setthumbnail($thumbnail);
    }

    /**
     * {@inheritDoc}
     */
    public function setimage_cate(?string $image_cate): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage_cate', [$image_cate]);

        return parent::setimage_cate($image_cate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoPath', []);

        return parent::getPhotoPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

}
